global:
  projectName: ruby
  env: qa

imageTag: ""

## Pod HealthCheck
readinessProbe:
  path: /healthcheck
  initialDelaySeconds: 20
livenessProbe:
  path: /healthcheck
  initialDelaySeconds: 20

## If you want to enable HPA
k8sObjectsEnabled:
  hpa: true
autoscaling:
  minReplicas: 2
  maxReplicas: 5

#+++++++++++++++++++++++++++++++++Developer Use++++++++++++++++++++++++++++++++++#
configMap:
  data:
    non-sensitive-key: non-sensitive-value
